[package]
name = "vidmerger"
version = "0.1.3"
authors = ["tgotwig <tgotwig@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
clap = { version = "3.0.0-beta.1", features = ["yaml"] }
term-painter = "0.2.4"
which = "4.0.2"
