[package]
authors = ["tgotwig <tgotwig@gmail.com>"]
edition = "2018"
name = "vidmerger"
version = "0.1.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.0.0-beta.1", features = ["yaml"]}
path-slash = "0.1.4"
regex = "1"
term-painter = "0.2.4"
which = "4.0.2"
