version: "3"

vars:
  VERSION:
    sh: grep '^version' Cargo.toml | head -n1 | cut -d '"' -f2

tasks:
  default:
    deps: [install, test]

  install:
    cmds:
      - |
        cargo install cross
        rustup component add clippy
        rustup component add rustfmt

  run: cargo run -- data/call_merger -y

  run_docker:
    deps: [build_linux_x64]
    cmds:
      - |
        docker build -t vidmerger .
        docker container run -it --rm -v ./data:/data vidmerger

  test: cargo test

  lint: cargo clippy

  build:
    cmds:
      - |
        task: build_linux_x64
        task: build_mac_x64
        task: build_win_x64
        task: shasum

  build_linux_x64:
    cmds:
      - |
        echo 'Building for Linux... 🐧'
        mkdir -p target
        sudo cross build --release --target=x86_64-unknown-linux-musl
        mkdir -p target/release-archives
        tar -C target/x86_64-unknown-linux-musl/release -czf target/release-archives/vidmerger-linux.tar.gz vidmerger

  build_mac_x64:
    cmds:
      - |
        echo 'Building for MacOS... 🍏'
        mkdir -p target
        rustup target add x86_64-apple-darwin
        sudo cargo build --release --target x86_64-apple-darwin
        mkdir -p target/release-archives
        tar -C target/x86_64-apple-darwin/release -czf target/release-archives/vidmerger-mac.tar.gz vidmerger

  build_win_x64:
    cmds:
      - |
        echo 'Building for Windows... 🏳️‍🌈'
        mkdir -p target
        sudo rm -r target/release
        sudo cross build --release --target x86_64-pc-windows-gnu
        mkdir -p target/release-archives
        cp target/x86_64-pc-windows-gnu/release/vidmerger.exe target/release-archives/vidmerger.exe

  shasum: shasum -a 256 target/release-archives/vidmerger*

  # TODO - test this
  publish_choco:
    cmds:
      - |
        choco pack
        Get-ChildItem *.nupkg | ren -NewName vidmerger.nupkg
        choco push vidmerger.nupkg --source https://push.chocolatey.org
        Remove-Item vidmerger.nupkg

  publish_dockerhub:
    cmds:
      - |
        docker build --no-cache -t vidmerger .
        docker tag vidmerger tgotwig/vidmerger:{{.VERSION}}
        docker push tgotwig/vidmerger:{{.VERSION}}
        docker tag vidmerger tgotwig/vidmerger
        docker push tgotwig/vidmerger
