version: '3'

tasks:
  default:
    deps: [install, test]

  install:
    cmds:
      - cargo install cross
      - rustup component add clippy

  run:
    cmds:
      - cargo run -- data --skip-wait --format mp4

  # TODO - fix this
  run_docker:
    deps: [build_linux_x64]
    cmds:
      - docker build -t vidmerger .
      - docker container run -it --rm -v `pwd`/data:/data vidmerger

  test:
    cmds:
      - cargo test -- --exact --nocapture $(name)

  test_units:
    cmds:
      - cargo test --bins -- --exact --nocapture $(name)

  lint:
    cmds:
      - cargo clippy

  # TODO - fix this
  build:
    deps: [build_linux_x64, build_mac_x64, build_win_x64, shasum]

  # TODO - fix this
  build_linux_x64:
    cmds:
      - echo 'Building for Linux... 🐧'
      - cross build --release --target=x86_64-unknown-linux-musl
      - mkdir -p target/release-archives
      - tar -C target/x86_64-unknown-linux-musl/release -czf target/release-archives/vidmerger-linux.tar.gz vidmerger

  # TODO - fix this
  build_mac_x64:
    cmds:
      - echo 'Building for MacOS... 🍏'
      - cross build --release --target=x86_64-apple-darwin
      - mkdir -p target/release-archives
      - tar -C target/x86_64-apple-darwin/release -czf target/release-archives/vidmerger-mac.tar.gz vidmerger

  build_win_x64:
    cmds:
      - echo 'Building for Windows... 🏳️‍🌈'
      - cross build --release --target x86_64-pc-windows-gnu
      - mkdir -p target/release-archives
      - rm -f target/release-archives/vidmerger.exe
      - cp target/x86_64-pc-windows-gnu/release/vidmerger.exe target/release-archives/vidmerger.exe

  shasum:
    cmds:
      - shasum -a 256 target/release-archives/vidmerger*
      - shasum -a 256 tools/vidmerger.exe

  # TODO - test this
  publish_choco:
    cmds:
      - choco pack
      - Get-ChildItem *.nupkg | ren -NewName vidmerger.nupkg
      - choco push vidmerger.nupkg --source https://push.chocolatey.org
      - Remove-Item vidmerger.nupkg

  # TODO - test this, automate versioning
  publish_dockerhub:
    cmds:
      - docker build --no-cache -t vidmerger .
      - docker tag vidmerger tgotwig/vidmerger:0.3.1
      - docker push tgotwig/vidmerger:0.3.1
      - docker tag vidmerger tgotwig/vidmerger
      - docker push tgotwig/vidmerger
