version: "3"

tasks:
  default:
    deps: [install, test]

  install:
    cmds:
      - |
        rustup component add clippy
        rustup component add rustfmt

  run: cargo run -- data/call_merger -y

  run_docker:
    cmds:
      - |
        docker build -t vidmerger .
        docker container run -it --rm -v ./data/call_merger:/data vidmerger

  test: cargo test

  lint: cargo clippy

  # TODO - test this
  publish_choco:
    cmds:
      - |
        choco pack
        Get-ChildItem *.nupkg | ren -NewName vidmerger.nupkg
        choco push vidmerger.nupkg --source https://push.chocolatey.org
        Remove-Item vidmerger.nupkg
